version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: travelixdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data


# version: '3'
# services:
#   postgres:
#     image: postgres:latest
#     volumes:
#       - /var/lib/postgresql/data:/var/lib/postgresql/data
#     # Otras configuraciones aquí
